name: Airbnb Search Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome
        sudo ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver
    
    - name: Run tests with retry
      run: |
        for i in {1..3}; do
          echo "Attempt $i of 3"
          pytest test_airbnb_search.py --html=report.html --self-contained-html || true
          if [ -f "report.html" ]; then
            break
          fi
          echo "Test attempt $i failed, retrying..."
          sleep 5
        done
    
    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: report.html
        retention-days: 7
    
    - name: Check test results
      if: failure()
      run: |
        if [ ! -f "report.html" ]; then
          echo "Test report not generated. All attempts failed."
          exit 1 